"""Evidence-based modality query routes for LightRAG API.

This module provides advanced query capabilities that filter results based on
evidence modalities (text, image, table, mathematical formulas) stored in the
knowledge graph relationships.
"""

import json
import logging
from typing import Any, Dict, List, Literal, Optional, Set
from enum import Enum

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from lightrag.api.utils_api import get_combined_auth_dependency

logger = logging.getLogger(__name__)


class ModalityType(str, Enum):
    """Supported evidence modality types."""
    TEXT = "text"
    IMAGE = "image"
    TABLE = "table"
    EQUATION = "equation"  # mathematical formulas
    MULTIMODAL = "multimodal"
    UNKNOWN = "unknown"


class LogicalOperator(str, Enum):
    """Logical operators for combining modality filters."""
    AND = "AND"
    OR = "OR"


class SearchMode(str, Enum):
    """Search mode for evidence query."""
    KEYWORD = "keyword"  # Direct keyword matching (fast, no LLM)
    LLM = "llm"  # Use LLM to extract keywords from natural language question


class ModalityQueryRequest(BaseModel):
    """Request model for evidence-based modality search."""

    search_mode: SearchMode = Field(
        default=SearchMode.KEYWORD,
        description="Search mode: 'keyword' for direct matching, 'llm' for natural language understanding",
    )

    query: str = Field(
        ...,
        description="For keyword mode: space-separated keywords. For LLM mode: natural language question.",
        examples=["dog chase", "What is the relationship between the dog and duck?"],
    )

    question: Optional[str] = Field(
        None,
        description="(Optional) Natural language question for answer generation when generate_answer=True",
        examples=["Why does the dog chase the duck?"],
    )

    generate_answer: bool = Field(
        default=False,
        description="Whether to generate a natural language answer using LLM based on filtered evidence",
    )
    
    modalities: List[ModalityType] = Field(
        default=[ModalityType.TEXT],
        description="List of modalities to filter by",
        examples=[["text", "image"], ["table", "equation"]]
    )
    
    modality_operator: LogicalOperator = Field(
        default=LogicalOperator.OR,
        description="Logical operator for combining modalities: AND requires all modalities, OR requires at least one"
    )
    
    mode: Literal["local", "global", "hybrid", "naive"] = Field(
        default="hybrid",
        description="Query mode for graph traversal"
    )
    
    min_evidence_count: int = Field(
        default=1,
        ge=1,
        description="Minimum number of evidence pieces required for a relationship to be included"
    )
    
    include_evidence_details: bool = Field(
        default=True,
        description="Include detailed evidence information (source chunks, modalities, document references) in the response"
    )
    
    top_k: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum number of results to return"
    )


class EvidenceDetail(BaseModel):
    """Detailed evidence information for a relationship."""
    chunk_id: str
    file_path: Optional[str] = None
    modality: str
    doc_id: Optional[str] = None
    timestamp: Optional[int] = None


class RelationshipWithEvidence(BaseModel):
    """Relationship with evidence metadata."""
    src_entity: str
    tgt_entity: str
    relation: str
    content: Optional[str] = None
    fact_key: Optional[str] = None
    evidence_total_count: int = 0
    evidence_doc_count: int = 0
    modalities: List[str] = Field(default_factory=list, description="List of modalities supporting this relationship")
    evidence_details: Optional[List[EvidenceDetail]] = None


class ModalityQueryResponse(BaseModel):
    """Response model for modality-based queries."""
    query: str
    search_mode: str = Field(description="Search mode used (keyword or llm)")
    modality_filter: List[str]
    modality_operator: str
    total_relationships_found: int
    relationships: List[RelationshipWithEvidence]
    extracted_keywords: Optional[Dict[str, List[str]]] = Field(
        None,
        description="Keywords extracted by LLM when search_mode=llm"
    )
    generated_answer: Optional[str] = Field(
        None,
        description="Natural language answer generated by LLM when generate_answer=True"
    )


def create_evidence_routes(rag, api_key: Optional[str] = None):
    """Create evidence-based query routes.
    
    Args:
        rag: LightRAG instance
        api_key: Optional API key for authentication
    
    Returns:
        APIRouter with evidence query endpoints
    """
    
    router = APIRouter(tags=["evidence"], prefix="/evidence")
    
    @router.post(
        "/query",
        response_model=ModalityQueryResponse,
        summary="Query with modality filtering",
        description="""Search the knowledge graph with advanced modality-based filtering.
        
        This endpoint allows you to:
        - Filter relationships by evidence modalities (text, image, table, equation)
        - Combine modality filters with AND/OR logic
        - Retrieve detailed evidence metadata
        - Get answers based only on evidence from specific modalities
        
        Example use cases:
        - Find relationships supported by images AND tables
        - Get all text-based evidence for a query
        - Search only mathematical formulas and equations
        """,
    )
    async def query_with_modality_filter(
        request: ModalityQueryRequest,
        auth: Any = Depends(get_combined_auth_dependency(api_key)),
    ) -> ModalityQueryResponse:
        """Query knowledge graph with modality-based evidence filtering."""
        try:
            logger.info(
                f"[EVIDENCE_QUERY] Mode: {request.search_mode} | Query: '{request.query}' | "
                f"Modalities: {request.modalities} | Operator: {request.modality_operator}"
            )
            
            # Step 1: Extract keywords (either direct or via LLM)
            extracted_keywords_dict = None
            query_terms = []
            
            if request.search_mode == SearchMode.LLM:
                # Use LLM to extract keywords from natural language
                logger.info("[EVIDENCE_QUERY] Using LLM to extract keywords")
                try:
                    query_param = QueryParam()
                    hl_keywords, ll_keywords = await extract_keywords_only(
                        request.query,
                        query_param,
                        asdict(rag),
                        rag.llm_response_cache
                    )
                    extracted_keywords_dict = {
                        "high_level": hl_keywords,
                        "low_level": ll_keywords
                    }
                    # Combine all keywords for filtering
                    all_keywords = hl_keywords + ll_keywords
                    query_terms = [term.lower().strip() for term in all_keywords if term.strip()]
                    logger.info(f"[EVIDENCE_QUERY] Extracted keywords: {extracted_keywords_dict}")
                except Exception as e:
                    logger.warning(f"[EVIDENCE_QUERY] LLM keyword extraction failed: {e}, falling back to direct query")
                    query_terms = [term.lower().strip() for term in request.query.split() if term.strip()]
            else:
                # Direct keyword matching
                query_terms = [term.lower().strip() for term in request.query.split() if term.strip()]
            
            # Step 2: Get all relationships from the graph
            relationships_with_evidence = []
            
            try:
                all_edges = await rag.chunk_entity_relation_graph.get_all_edges()
                logger.info(f"[EVIDENCE_QUERY] Retrieved {len(all_edges)} total edges from graph")
            except Exception as e:
                logger.error(f"[EVIDENCE_QUERY] Failed to retrieve edges: {e}")
                all_edges = []
            
            # Filter edges based on modality criteria
            modality_set = set(m.value for m in request.modalities)
            
            for edge in all_edges:
                try:
                    # Extract source and target from edge dict
                    src_id = edge.get("source", "")
                    tgt_id = edge.get("target", "")
                    
                    if not src_id or not tgt_id:
                        continue
                    
                    # Extract modality information from edge
                    edge_modalities_str = edge.get("modality", "")
                    if not edge_modalities_str:
                        continue
                    
                    # Parse modalities (comma-separated string)
                    edge_modalities = set(m.strip().lower() for m in edge_modalities_str.split(",") if m.strip())
                    
                    # Apply modality filter based on operator
                    matches = False
                    if request.modality_operator == LogicalOperator.AND:
                        # All requested modalities must be present
                        matches = modality_set.issubset(edge_modalities)
                    else:  # OR
                        # At least one requested modality must be present
                        matches = bool(modality_set.intersection(edge_modalities))
                    
                    if not matches:
                        continue
                    
                    # Check minimum evidence count
                    evidence_count = edge.get("evidence_total_count", 0)
                    if evidence_count < request.min_evidence_count:
                        continue
                    
                    # Apply query filtering (search in entities, relations, and content)
                    if query_terms:
                        # Combine searchable fields
                        searchable_text = " ".join([
                            src_id.lower(),
                            tgt_id.lower(),
                            edge.get("keywords", "").lower(),
                            edge.get("content", "").lower()
                        ])
                        
                        # Check if any query term matches
                        if not any(term in searchable_text for term in query_terms):
                            continue
                    
                    # Parse evidence details if requested
                    evidence_details = None
                    if request.include_evidence_details:
                        evidence_summary_json = edge.get("evidence_summary_json")
                        if evidence_summary_json:
                            try:
                                evidence_summary = json.loads(evidence_summary_json)
                                evidence_details = [
                                    EvidenceDetail(
                                        chunk_id=src.get("chunk_id", ""),
                                        file_path=src.get("file_path"),
                                        modality=src.get("modality", "unknown"),
                                        doc_id=src.get("doc_id"),
                                        timestamp=src.get("timestamp"),
                                    )
                                    for src in evidence_summary.get("sources", [])
                                ]
                            except json.JSONDecodeError:
                                logger.warning(f"Failed to parse evidence_summary_json for edge {src_id}->{tgt_id}")
                    
                    relationship = RelationshipWithEvidence(
                        src_entity=src_id,
                        tgt_entity=tgt_id,
                        relation=edge.get("keywords", ""),
                        content=edge.get("content"),
                        fact_key=edge.get("fact_key"),
                        evidence_total_count=evidence_count,
                        evidence_doc_count=edge.get("evidence_doc_count", 0),
                        modalities=list(edge_modalities),
                        evidence_details=evidence_details,
                    )
                    
                    relationships_with_evidence.append(relationship)
                    
                except Exception as e:
                    logger.debug(f"[EVIDENCE_QUERY] Error processing edge: {e}")
                    continue
            
            # Sort by evidence count (descending) and limit to top_k
            relationships_with_evidence.sort(
                key=lambda r: r.evidence_total_count,
                reverse=True
            )
            relationships_with_evidence = relationships_with_evidence[:request.top_k]
            
            logger.info(
                f"[EVIDENCE_QUERY] Found {len(relationships_with_evidence)} relationships "
                f"matching modality filter"
            )
            
            # Step 3: Generate answer if requested
            generated_answer = None
            logger.info(f"[EVIDENCE_QUERY] Checking answer generation: generate_answer={request.generate_answer}, relationships_count={len(relationships_with_evidence)}")
            
            if request.generate_answer and relationships_with_evidence:
                logger.info("[EVIDENCE_QUERY] Starting answer generation from filtered evidence")
                try:
                    # Build context from filtered relationships
                    entities_context = []
                    relations_context = []
                    
                    for rel in relationships_with_evidence:
                        relations_context.append({
                            "src_id": rel.src_entity,
                            "tgt_id": rel.tgt_entity,
                            "keywords": rel.relation,
                            "content": rel.content or "",
                            "modalities": ", ".join(rel.modalities),
                            "evidence_count": rel.evidence_total_count
                        })
                        entities_context.append({"entity_name": rel.src_entity})
                        entities_context.append({"entity_name": rel.tgt_entity})
                    
                    # Remove duplicate entities
                    seen_entities = set()
                    unique_entities = []
                    for ent in entities_context:
                        if ent["entity_name"] not in seen_entities:
                            unique_entities.append(ent)
                            seen_entities.add(ent["entity_name"])
                    
                    # Use the question field if provided, otherwise use the original query
                    question_for_llm = request.question or request.query
                    
                    # Build prompt for answer generation
                    operator_str = f" {request.modality_operator.value} "
                    modalities_str = operator_str.join([m.value for m in request.modalities])
                    modality_info = f" (filtered by {modalities_str} modalities)"
                    
                    context_text = f"""Based on the following knowledge graph relationships{modality_info}:\n\n"""
                    context_text += "Relationships:\n"
                    for i, rel in enumerate(relations_context[:10], 1):  # Limit to top 10 for context
                        context_text += f"{i}. {rel['src_id']} -{rel['keywords']}-> {rel['tgt_id']}"
                        context_text += f" (Evidence: {rel['evidence_count']}, Modalities: {rel['modalities']})\n"
                        if rel['content']:
                            context_text += f"   Description: {rel['content'][:200]}...\n"
                    
                    prompt = f"{context_text}\n\nQuestion: {question_for_llm}\n\nAnswer:"
                    logger.info(f"[EVIDENCE_QUERY] Prompt length: {len(prompt)} chars")
                    
                    # Call LLM
                    llm_func = rag.llm_model_func
                    logger.info(f"[EVIDENCE_QUERY] Calling LLM function: {llm_func}")
                    generated_answer = await llm_func(prompt)
                    logger.info(f"[EVIDENCE_QUERY] Answer generated successfully, length: {len(generated_answer) if generated_answer else 0} chars")
                    
                except Exception as e:
                    logger.error(f"[EVIDENCE_QUERY] Answer generation failed: {e}", exc_info=True)
                    generated_answer = None
            
            return ModalityQueryResponse(
                query=request.query,
                search_mode=request.search_mode.value,
                modality_filter=[m.value for m in request.modalities],
                modality_operator=request.modality_operator.value,
                total_relationships_found=len(relationships_with_evidence),
                relationships=relationships_with_evidence,
                extracted_keywords=extracted_keywords_dict,
                generated_answer=generated_answer,
            )
            
        except Exception as e:
            logger.error(f"[EVIDENCE_QUERY] Query failed: {e}", exc_info=True)
            raise HTTPException(
                status_code=500,
                detail=f"Evidence query failed: {str(e)}"
            )
    
    @router.get(
        "/modalities/stats",
        summary="Get modality statistics",
        description="""Get statistics about modality distribution in the knowledge graph.
        
        Returns counts and percentages of relationships by modality type.
        """,
    )
    async def get_modality_stats(
        auth: Any = Depends(get_combined_auth_dependency(api_key)),
    ) -> Dict[str, Any]:
        """Get statistics about evidence modalities in the knowledge graph."""
        try:
            all_edges = await rag.chunk_entity_relation_graph.get_all_edges()
            
            modality_counts = {}
            total_with_evidence = 0
            total_edges = len(all_edges)
            
            for edge in all_edges:
                modalities_str = edge.get("modality", "")
                if modalities_str:
                    total_with_evidence += 1
                    for modality in modalities_str.split(","):
                        modality = modality.strip().lower()
                        if modality:
                            modality_counts[modality] = modality_counts.get(modality, 0) + 1
            
            # Calculate percentages
            modality_stats = {
                mod: {
                    "count": count,
                    "percentage": round(count / total_with_evidence * 100, 2) if total_with_evidence > 0 else 0
                }
                for mod, count in modality_counts.items()
            }
            
            return {
                "total_edges": total_edges,
                "edges_with_evidence": total_with_evidence,
                "edges_without_evidence": total_edges - total_with_evidence,
                "modality_distribution": modality_stats,
            }
            
        except Exception as e:
            logger.error(f"Failed to get modality stats: {e}", exc_info=True)
            raise HTTPException(
                status_code=500,
                detail=f"Failed to get modality statistics: {str(e)}"
            )
    
    return router